---
- hosts: gate_srv, exims_local
  become: true
  become_user: root
  tasks:
    - include_tasks:
        file: tasks/update-upgrade-reboot.yml

    - name: Install main soft
      apt:
        name:
          - python-apt
          - mc
          - net-tools
          - fail2ban
          - inetutils-traceroute
          - iptables-persistent
        state: latest
        update_cache: yes

- hosts: gate_srv
  become: true
  become_user: root
  tasks:
    # Настройка iptables
    - name: Edit sysctl.conf
      copy:
        dest: /etc/sysctl.conf
        content: |
          net.ipv4.ip_forward=1
      notify: "Apply core settings"

    - block:
      - name: Даём интернет до брокеров
        iptables:
          table: nat
          chain: POSTROUTING
          destination: "{{ hostvars[broker_inv].ansible_host }}"
          out_interface: "{{ ext_iface }}"
          jump: MASQUERADE
        loop: "{{ groups['brokers'] }}"
        loop_control:
          loop_var: broker_inv
        notify: "Save iptables"

      - name: ACCEPT all from local interface
        iptables:
          chain: INPUT
          in_interface: "{{ local_iface }}"
          jump: ACCEPT
        notify: "Save iptables"
        when: local_iface is defined

      # base

      - include_tasks:
          file: tasks/firewall-base.yml
      tags:
        - firewall

  handlers:
    - name: Apply core settings
      shell:
        cmd: "sysctl -w 'net.ipv4.ip_forward=1'"

    - name: Save iptables
      shell: netfilter-persistent save

###                                         ПЕРЕНЕСЛИ В БЛОК № 5, так как нужные переменные получаем только в БЛОКЕ № 4
### Настройка Firewall для exims_local
# - hosts: exims_local
#   become: true
#   become_user: root
#   tasks:
#     # Настройка iptables
#     - name: Edit sysctl.conf
#       copy:
#         dest: /etc/sysctl.conf
#         content: |
#           net.ipv4.ip_forward=1
#           net.core.wmem_default=1048576
#           net.core.rmem_default=1048576
#           net.ipv4.tcp_rmem=4096        1048576 6291456
#           net.ipv4.tcp_wmem=4096        1048576 4194304
#       notify: "Apply core settings"

#     - block:
#       - name: ACCEPT all from local interface
#         iptables:
#           chain: INPUT
#           in_interface: "{{ local_iface }}"
#           jump: ACCEPT
#         notify: "Save iptables"
#         when: local_iface is defined

#       - name: Incomming SMTP
#         iptables:
#           chain: INPUT
#           protocol: tcp
#           destination_port: "25"
#           ctstate: NEW
#           syn: match
#           jump: ACCEPT
#         notify: "Save iptables"

#       # base

#       - include_tasks:
#           file: tasks/firewall-base.yml
#       tags:
#         - firewall

  # handlers:
  #   - name: Apply core settings
  #     shell:
  #       cmd: "sysctl -w {{ sysctlstr }}"
  #     loop:
  #       - 'net.ipv4.ip_forward=1'
  #       - 'net.core.rmem_default=1048576'
  #       - 'net.core.wmem_default=1048576'
  #       - 'net.ipv4.tcp_rmem="4096 1048576 6291456"'
  #       - 'net.ipv4.tcp_wmem="4096 1048576 6291456"'
  #     loop_control:
  #       loop_var: sysctlstr

  #   - name: Save iptables
  #     shell: netfilter-persistent save

- hosts: brokers
  become: true
  become_user: root
  tasks:
    - include_tasks:
        file: tasks/update-upgrade-reboot.yml

    - name: Install main soft
      apt:
        name:
          - python-apt
          - mc
          - net-tools
          - fail2ban
          - inetutils-traceroute
          - openvpn
          - iptables-persistent
        state: latest
        update_cache: yes

### Сюда добавляем все хосты, для которых должен быть минимизирован полный интернет

- hosts: exim_core
  become: true
  become_user: root
  tasks:
    - name: Give internet for host
      iptables:
        table: nat
        chain: POSTROUTING
        source: "{{ ansible_host }}"
        out_interface: "{{ hostvars['mailGate01'].ext_iface }}"
        jump: MASQUERADE
      delegate_to: "{{ hostvars['mailGate01'].ansible_host }}"

    - include_tasks:
        file: tasks/update-upgrade-reboot.yml

    - name: Install main soft
      apt:
        name:
          - python-apt
          - mc
          - net-tools
          - fail2ban
          - inetutils-traceroute
          - openvpn
          - exim4
        state: latest
        update_cache: yes

    - name: Remove internet for host
      iptables:
        table: nat
        chain: POSTROUTING
        source: "{{ ansible_host }}"
        out_interface: "{{ hostvars['mailGate01'].ext_iface }}"
        jump: MASQUERADE
        state: absent
      delegate_to: "{{ hostvars['mailGate01'].ansible_host }}"